/* -- This file is automatically generated -- */ 
/* 

  Copyright (C) 2002, 2004 ST Microelectronics, Inc.  All Rights Reserved. 

  This program is free software; you can redistribute it and/or modify it 
  under the terms of version 2 of the GNU General Public License as 
  published by the Free Software Foundation. 
  This program is distributed in the hope that it would be useful, but 
  WITHOUT ANY WARRANTY; without even the implied warranty of 
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 

  Further, this software is distributed without any warranty that it is 
  free of the rightful claim of any third person regarding infringement 
  or the like.  Any license provided herein, whether implied or 
  otherwise, applies only to this software file.  Patent licenses, if 
  any, provided herein do not apply to combinations of this program with 
  other software, or any other product whatsoever. 
  You should have received a copy of the GNU General Public License along 
  with this program; if not, write the Free Software Foundation, Inc., 59 
  Temple Place - Suite 330, Boston MA 02111-1307, USA. 

  Contact information:  ST Microelectronics, Inc., 
  , or: 

  http://www.st.com 

  For further information regarding this notice, see: 

  http: 
*/ 

// AUTOMATICALLY GENERATED FROM MDS DATA BASE !!! 
//
// Generate pseudo instruction encoding and decoding information.
/////////////////////////////////////
/////////////////////////////////////
#include "topcode.h"
#include "isa_pseudo_gen.h"
 
main()
{
  Machine_To_Pseudo(TOP_cmpge_r_b, TOP_cmple_r_b);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(0)", "OPND(0)");
  Map_Arg("OPND(1)", "OPND(1)");

  Pseudo_To_Machine(TOP_cmple_r_b, TOP_cmpge_r_b);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(0)", "OPND(0)");
  Map_Arg("OPND(1)", "OPND(1)");


  Machine_To_Pseudo(TOP_cmpge_r_r, TOP_cmple_r_r);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(0)", "OPND(0)");
  Map_Arg("OPND(1)", "OPND(1)");

  Pseudo_To_Machine(TOP_cmple_r_r, TOP_cmpge_r_r);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(0)", "OPND(0)");
  Map_Arg("OPND(1)", "OPND(1)");


  Machine_To_Pseudo(TOP_cmpgeu_r_b, TOP_cmpleu_r_b);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(0)", "OPND(0)");
  Map_Arg("OPND(1)", "OPND(1)");

  Pseudo_To_Machine(TOP_cmpleu_r_b, TOP_cmpgeu_r_b);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(0)", "OPND(0)");
  Map_Arg("OPND(1)", "OPND(1)");


  Machine_To_Pseudo(TOP_cmpgeu_r_r, TOP_cmpleu_r_r);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(0)", "OPND(0)");
  Map_Arg("OPND(1)", "OPND(1)");

  Pseudo_To_Machine(TOP_cmpleu_r_r, TOP_cmpgeu_r_r);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(0)", "OPND(0)");
  Map_Arg("OPND(1)", "OPND(1)");


  Machine_To_Pseudo(TOP_cmpgt_r_b, TOP_cmplt_r_b);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(0)", "OPND(0)");
  Map_Arg("OPND(1)", "OPND(1)");

  Pseudo_To_Machine(TOP_cmplt_r_b, TOP_cmpgt_r_b);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(0)", "OPND(0)");
  Map_Arg("OPND(1)", "OPND(1)");


  Machine_To_Pseudo(TOP_cmpgt_r_r, TOP_cmplt_r_r);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(0)", "OPND(0)");
  Map_Arg("OPND(1)", "OPND(1)");

  Pseudo_To_Machine(TOP_cmplt_r_r, TOP_cmpgt_r_r);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(0)", "OPND(0)");
  Map_Arg("OPND(1)", "OPND(1)");


  Machine_To_Pseudo(TOP_cmplef_n_b, TOP_cmpgef_n_b);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(1)", "OPND(0)");
  Map_Arg("OPND(0)", "OPND(1)");

  Pseudo_To_Machine(TOP_cmpgef_n_b, TOP_cmplef_n_b);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(0)", "OPND(1)");
  Map_Arg("OPND(1)", "OPND(0)");


  Machine_To_Pseudo(TOP_cmplef_n_r, TOP_cmpgef_n_r);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(1)", "OPND(0)");
  Map_Arg("OPND(0)", "OPND(1)");

  Pseudo_To_Machine(TOP_cmpgef_n_r, TOP_cmplef_n_r);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(0)", "OPND(1)");
  Map_Arg("OPND(1)", "OPND(0)");


  Machine_To_Pseudo(TOP_cmpltf_n_b, TOP_cmpgtf_n_b);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(1)", "OPND(0)");
  Map_Arg("OPND(0)", "OPND(1)");

  Pseudo_To_Machine(TOP_cmpgtf_n_b, TOP_cmpltf_n_b);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(0)", "OPND(1)");
  Map_Arg("OPND(1)", "OPND(0)");


  Machine_To_Pseudo(TOP_cmpltf_n_r, TOP_cmpgtf_n_r);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(1)", "OPND(0)");
  Map_Arg("OPND(0)", "OPND(1)");

  Pseudo_To_Machine(TOP_cmpgtf_n_r, TOP_cmpltf_n_r);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(0)", "OPND(1)");
  Map_Arg("OPND(1)", "OPND(0)");


  Machine_To_Pseudo(TOP_idle, TOP_goto);
  Require("OPND(0) == 0");

  Pseudo_To_Machine(TOP_goto, TOP_idle);
  Map_Arg("OPND(0)", "0");


  Machine_To_Pseudo(TOP_mfb, TOP_slctf_i);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(0)", "OPND(0)");
  Require("OPND(1) == 0");
  Require("OPND(2) == 1");

  Pseudo_To_Machine(TOP_slctf_i, TOP_mfb);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(0)", "OPND(0)");
  Map_Arg("OPND(1)", "0");
  Map_Arg("OPND(2)", "1");


  Machine_To_Pseudo(TOP_mov_r, TOP_add_r);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Require("OPND(0) == 0");
  Map_Arg("OPND(0)", "OPND(1)");

  Pseudo_To_Machine(TOP_add_r, TOP_mov_r);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(0)", "0");
  Map_Arg("OPND(1)", "OPND(0)");


  Machine_To_Pseudo(TOP_mov_i, TOP_add_i);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Require("OPND(0) == 0");
  Map_Arg("OPND(0)", "OPND(1)");

  Pseudo_To_Machine(TOP_add_i, TOP_mov_i);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(0)", "0");
  Map_Arg("OPND(1)", "OPND(0)");


  Machine_To_Pseudo(TOP_mov_ii, TOP_add_ii);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Require("OPND(0) == 0");
  Map_Arg("OPND(0)", "OPND(1)");

  Pseudo_To_Machine(TOP_add_ii, TOP_mov_ii);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(0)", "0");
  Map_Arg("OPND(1)", "OPND(0)");


  Machine_To_Pseudo(TOP_mtb, TOP_orl_r_b);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(0)", "OPND(0)");
  Require("OPND(1) == 0");

  Pseudo_To_Machine(TOP_orl_r_b, TOP_mtb);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(0)", "OPND(0)");
  Map_Arg("OPND(1)", "0");


  Machine_To_Pseudo(TOP_nop, TOP_add_r);
  Require("RESULT(0) == 0");
  Require("OPND(0) == 0");
  Require("OPND(1) == 0");

  Pseudo_To_Machine(TOP_add_r, TOP_nop);
  Map_Arg("RESULT(0)", "0");
  Map_Arg("OPND(0)", "0");
  Map_Arg("OPND(1)", "0");


  Machine_To_Pseudo(TOP_return, TOP_igoto);

  Pseudo_To_Machine(TOP_igoto, TOP_return);


  Machine_To_Pseudo(TOP_syncins, TOP_goto);
  Require("OPND(0) == 1");

  Pseudo_To_Machine(TOP_goto, TOP_syncins);
  Map_Arg("OPND(0)", "1");


  Machine_To_Pseudo(TOP_zxtb, TOP_and_i);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(0)", "OPND(0)");
  Require("OPND(1) == 255");

  Pseudo_To_Machine(TOP_and_i, TOP_zxtb);
  Map_Arg("RESULT(0)", "RESULT(0)");
  Map_Arg("OPND(0)", "OPND(0)");
  Map_Arg("OPND(1)", "255");



  ISA_Pseudo_End();
  return 0;
}
