/* -- This file is automatically generated -- */ 
/* 

  Copyright (C) 2002 ST Microelectronics, Inc.  All Rights Reserved. 

  This program is free software; you can redistribute it and/or modify it 
  under the terms of version 2 of the GNU General Public License as 
  published by the Free Software Foundation. 
  This program is distributed in the hope that it would be useful, but 
  WITHOUT ANY WARRANTY; without even the implied warranty of 
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 

  Further, this software is distributed without any warranty that it is 
  free of the rightful claim of any third person regarding infringement 
  or the like.  Any license provided herein, whether implied or 
  otherwise, applies only to this software file.  Patent licenses, if 
  any, provided herein do not apply to combinations of this program with 
  other software, or any other product whatsoever. 
  You should have received a copy of the GNU General Public License along 
  with this program; if not, write the Free Software Foundation, Inc., 59 
  Temple Place - Suite 330, Boston MA 02111-1307, USA. 

  Contact information:  ST Microelectronics, Inc., 
  , or: 

  http://www.st.com 

  For further information regarding this notice, see: 

  http: 
*/ 

//  
//  Generate ISA bundle information 
/////////////////////////////////////// 

#include <stddef.h> 
#include "topcode.h" 
#include "isa_bundle_gen.h" 

main() 
{ 
  ISA_EXEC_UNIT_TYPE 
		    S0_Unit, 
		    S1_Unit, 
		    S2_Unit, 
		    S3_Unit; 

  ISA_Bundle_Begin("st200", 128); 

  /* ===== Specification for bundle packing  ===== */ 
  ISA_Bundle_Pack_Create(ISA_Bundle_Pack_Little_Endian); 
  Pack_Template(0, 0, 0); 
  Pack_Slot(0, 0, 0, 32); 
  Pack_Slot(1, 0, 32, 32); 
  Pack_Slot(2, 0, 64, 32); 
  Pack_Slot(3, 0, 96, 32); 

  /* ===== Specification for S0_Unit Type ===== */ 
  S0_Unit = ISA_Exec_Unit_Type_Create("S0_Unit", NULL); 
  Instruction_Exec_Unit_Group(S0_Unit, 
		 TOP_nop, 
		 TOP_mov_r, 
		 TOP_mov_i, 
		 TOP_mtb, 
		 TOP_mfb, 
		 TOP_add_r, 
		 TOP_add_i, 
		 TOP_addcg, 
		 TOP_and_r, 
		 TOP_and_i, 
		 TOP_andc_r, 
		 TOP_andc_i, 
		 TOP_andl_r_r, 
		 TOP_andl_r_b, 
		 TOP_andl_i_r, 
		 TOP_andl_i_b, 
		 TOP_break, 
		 TOP_bswap_r, 
		 TOP_cmpeq_r_r, 
		 TOP_cmpeq_r_b, 
		 TOP_cmpeq_i_r, 
		 TOP_cmpeq_i_b, 
		 TOP_cmpge_r_r, 
		 TOP_cmpge_r_b, 
		 TOP_cmpge_i_r, 
		 TOP_cmpge_i_b, 
		 TOP_cmpgeu_r_r, 
		 TOP_cmpgeu_r_b, 
		 TOP_cmpgeu_i_r, 
		 TOP_cmpgeu_i_b, 
		 TOP_cmpgt_r_r, 
		 TOP_cmpgt_r_b, 
		 TOP_cmpgt_i_r, 
		 TOP_cmpgt_i_b, 
		 TOP_cmpgtu_r_r, 
		 TOP_cmpgtu_r_b, 
		 TOP_cmpgtu_i_r, 
		 TOP_cmpgtu_i_b, 
		 TOP_cmple_r_r, 
		 TOP_cmple_r_b, 
		 TOP_cmple_i_r, 
		 TOP_cmple_i_b, 
		 TOP_cmpleu_r_r, 
		 TOP_cmpleu_r_b, 
		 TOP_cmpleu_i_r, 
		 TOP_cmpleu_i_b, 
		 TOP_cmplt_r_r, 
		 TOP_cmplt_r_b, 
		 TOP_cmplt_i_r, 
		 TOP_cmplt_i_b, 
		 TOP_cmpltu_r_r, 
		 TOP_cmpltu_r_b, 
		 TOP_cmpltu_i_r, 
		 TOP_cmpltu_i_b, 
		 TOP_cmpne_r_r, 
		 TOP_cmpne_r_b, 
		 TOP_cmpne_i_r, 
		 TOP_cmpne_i_b, 
		 TOP_divs, 
		 TOP_max_r, 
		 TOP_max_i, 
		 TOP_maxu_r, 
		 TOP_maxu_i, 
		 TOP_min_r, 
		 TOP_min_i, 
		 TOP_minu_r, 
		 TOP_minu_i, 
		 TOP_nandl_r_r, 
		 TOP_nandl_r_b, 
		 TOP_nandl_i_r, 
		 TOP_nandl_i_b, 
		 TOP_norl_r_r, 
		 TOP_norl_r_b, 
		 TOP_norl_i_r, 
		 TOP_norl_i_b, 
		 TOP_or_r, 
		 TOP_or_i, 
		 TOP_orc_r, 
		 TOP_orc_i, 
		 TOP_orl_r_r, 
		 TOP_orl_r_b, 
		 TOP_orl_i_r, 
		 TOP_orl_i_b, 
		 TOP_sbrk, 
		 TOP_sh1add_r, 
		 TOP_sh1add_i, 
		 TOP_sh2add_r, 
		 TOP_sh2add_i, 
		 TOP_sh3add_r, 
		 TOP_sh3add_i, 
		 TOP_sh4add_r, 
		 TOP_sh4add_i, 
		 TOP_shl_r, 
		 TOP_shl_i, 
		 TOP_shr_r, 
		 TOP_shr_i, 
		 TOP_shru_r, 
		 TOP_shru_i, 
		 TOP_slct_r, 
		 TOP_slct_i, 
		 TOP_slctf_r, 
		 TOP_slctf_i, 
		 TOP_sub_r, 
		 TOP_sub_i, 
		 TOP_syscall, 
		 TOP_sxtb_r, 
		 TOP_sxth_r, 
		 TOP_xor_r, 
		 TOP_xor_i, 
		 TOP_send_i, 
		 TOP_recv_i, 
		 TOP_mulh_r, 
		 TOP_mulh_i, 
		 TOP_mulhh_r, 
		 TOP_mulhh_i, 
		 TOP_mulhhu_r, 
		 TOP_mulhhu_i, 
		 TOP_mulhs_r, 
		 TOP_mulhs_i, 
		 TOP_mulhu_r, 
		 TOP_mulhu_i, 
		 TOP_mull_r, 
		 TOP_mull_i, 
		 TOP_mullh_r, 
		 TOP_mullh_i, 
		 TOP_mullhu_r, 
		 TOP_mullhu_i, 
		 TOP_mulll_r, 
		 TOP_mulll_i, 
		 TOP_mulllu_r, 
		 TOP_mulllu_i, 
		 TOP_mullu_r, 
		 TOP_mullu_i, 
		 TOP_ldb, 
		 TOP_ldb_d, 
		 TOP_ldbu, 
		 TOP_ldbu_d, 
		 TOP_ldh, 
		 TOP_ldh_d, 
		 TOP_ldhu, 
		 TOP_ldhu_d, 
		 TOP_ldw, 
		 TOP_ldw_d, 
		 TOP_sync, 
		 TOP_pft, 
		 TOP_prgadd, 
		 TOP_prgset, 
		 TOP_stb, 
		 TOP_sth, 
		 TOP_stw, 
		 TOP_br, 
		 TOP_brf, 
		 TOP_return, 
		 TOP_call, 
		 TOP_goto, 
		 TOP_icall, 
		 TOP_igoto, 
		 TOP_prgins, 
		 TOP_rfi, 
		 TOP_UNDEFINED); 

  /* ===== Specification for S1_Unit Type ===== */ 
  S1_Unit = ISA_Exec_Unit_Type_Create("S1_Unit", NULL); 
  Instruction_Exec_Unit_Group(S1_Unit, 
		 TOP_nop, 
		 TOP_mov_r, 
		 TOP_mov_i, 
		 TOP_mtb, 
		 TOP_mfb, 
		 TOP_add_r, 
		 TOP_add_i, 
		 TOP_addcg, 
		 TOP_and_r, 
		 TOP_and_i, 
		 TOP_andc_r, 
		 TOP_andc_i, 
		 TOP_andl_r_r, 
		 TOP_andl_r_b, 
		 TOP_andl_i_r, 
		 TOP_andl_i_b, 
		 TOP_break, 
		 TOP_bswap_r, 
		 TOP_cmpeq_r_r, 
		 TOP_cmpeq_r_b, 
		 TOP_cmpeq_i_r, 
		 TOP_cmpeq_i_b, 
		 TOP_cmpge_r_r, 
		 TOP_cmpge_r_b, 
		 TOP_cmpge_i_r, 
		 TOP_cmpge_i_b, 
		 TOP_cmpgeu_r_r, 
		 TOP_cmpgeu_r_b, 
		 TOP_cmpgeu_i_r, 
		 TOP_cmpgeu_i_b, 
		 TOP_cmpgt_r_r, 
		 TOP_cmpgt_r_b, 
		 TOP_cmpgt_i_r, 
		 TOP_cmpgt_i_b, 
		 TOP_cmpgtu_r_r, 
		 TOP_cmpgtu_r_b, 
		 TOP_cmpgtu_i_r, 
		 TOP_cmpgtu_i_b, 
		 TOP_cmple_r_r, 
		 TOP_cmple_r_b, 
		 TOP_cmple_i_r, 
		 TOP_cmple_i_b, 
		 TOP_cmpleu_r_r, 
		 TOP_cmpleu_r_b, 
		 TOP_cmpleu_i_r, 
		 TOP_cmpleu_i_b, 
		 TOP_cmplt_r_r, 
		 TOP_cmplt_r_b, 
		 TOP_cmplt_i_r, 
		 TOP_cmplt_i_b, 
		 TOP_cmpltu_r_r, 
		 TOP_cmpltu_r_b, 
		 TOP_cmpltu_i_r, 
		 TOP_cmpltu_i_b, 
		 TOP_cmpne_r_r, 
		 TOP_cmpne_r_b, 
		 TOP_cmpne_i_r, 
		 TOP_cmpne_i_b, 
		 TOP_divs, 
		 TOP_max_r, 
		 TOP_max_i, 
		 TOP_maxu_r, 
		 TOP_maxu_i, 
		 TOP_min_r, 
		 TOP_min_i, 
		 TOP_minu_r, 
		 TOP_minu_i, 
		 TOP_nandl_r_r, 
		 TOP_nandl_r_b, 
		 TOP_nandl_i_r, 
		 TOP_nandl_i_b, 
		 TOP_norl_r_r, 
		 TOP_norl_r_b, 
		 TOP_norl_i_r, 
		 TOP_norl_i_b, 
		 TOP_or_r, 
		 TOP_or_i, 
		 TOP_orc_r, 
		 TOP_orc_i, 
		 TOP_orl_r_r, 
		 TOP_orl_r_b, 
		 TOP_orl_i_r, 
		 TOP_orl_i_b, 
		 TOP_sbrk, 
		 TOP_sh1add_r, 
		 TOP_sh1add_i, 
		 TOP_sh2add_r, 
		 TOP_sh2add_i, 
		 TOP_sh3add_r, 
		 TOP_sh3add_i, 
		 TOP_sh4add_r, 
		 TOP_sh4add_i, 
		 TOP_shl_r, 
		 TOP_shl_i, 
		 TOP_shr_r, 
		 TOP_shr_i, 
		 TOP_shru_r, 
		 TOP_shru_i, 
		 TOP_slct_r, 
		 TOP_slct_i, 
		 TOP_slctf_r, 
		 TOP_slctf_i, 
		 TOP_sub_r, 
		 TOP_sub_i, 
		 TOP_syscall, 
		 TOP_sxtb_r, 
		 TOP_sxth_r, 
		 TOP_xor_r, 
		 TOP_xor_i, 
		 TOP_send_i, 
		 TOP_recv_i, 
		 TOP_ldb, 
		 TOP_ldb_d, 
		 TOP_ldbu, 
		 TOP_ldbu_d, 
		 TOP_ldh, 
		 TOP_ldh_d, 
		 TOP_ldhu, 
		 TOP_ldhu_d, 
		 TOP_ldw, 
		 TOP_ldw_d, 
		 TOP_sync, 
		 TOP_pft, 
		 TOP_prgadd, 
		 TOP_prgset, 
		 TOP_stb, 
		 TOP_sth, 
		 TOP_stw, 
		 TOP_imml, 
		 TOP_immr, 
		 TOP_UNDEFINED); 

  /* ===== Specification for S2_Unit Type ===== */ 
  S2_Unit = ISA_Exec_Unit_Type_Create("S2_Unit", NULL); 
  Instruction_Exec_Unit_Group(S2_Unit, 
		 TOP_nop, 
		 TOP_mov_r, 
		 TOP_mov_i, 
		 TOP_mtb, 
		 TOP_mfb, 
		 TOP_add_r, 
		 TOP_add_i, 
		 TOP_addcg, 
		 TOP_and_r, 
		 TOP_and_i, 
		 TOP_andc_r, 
		 TOP_andc_i, 
		 TOP_andl_r_r, 
		 TOP_andl_r_b, 
		 TOP_andl_i_r, 
		 TOP_andl_i_b, 
		 TOP_break, 
		 TOP_bswap_r, 
		 TOP_cmpeq_r_r, 
		 TOP_cmpeq_r_b, 
		 TOP_cmpeq_i_r, 
		 TOP_cmpeq_i_b, 
		 TOP_cmpge_r_r, 
		 TOP_cmpge_r_b, 
		 TOP_cmpge_i_r, 
		 TOP_cmpge_i_b, 
		 TOP_cmpgeu_r_r, 
		 TOP_cmpgeu_r_b, 
		 TOP_cmpgeu_i_r, 
		 TOP_cmpgeu_i_b, 
		 TOP_cmpgt_r_r, 
		 TOP_cmpgt_r_b, 
		 TOP_cmpgt_i_r, 
		 TOP_cmpgt_i_b, 
		 TOP_cmpgtu_r_r, 
		 TOP_cmpgtu_r_b, 
		 TOP_cmpgtu_i_r, 
		 TOP_cmpgtu_i_b, 
		 TOP_cmple_r_r, 
		 TOP_cmple_r_b, 
		 TOP_cmple_i_r, 
		 TOP_cmple_i_b, 
		 TOP_cmpleu_r_r, 
		 TOP_cmpleu_r_b, 
		 TOP_cmpleu_i_r, 
		 TOP_cmpleu_i_b, 
		 TOP_cmplt_r_r, 
		 TOP_cmplt_r_b, 
		 TOP_cmplt_i_r, 
		 TOP_cmplt_i_b, 
		 TOP_cmpltu_r_r, 
		 TOP_cmpltu_r_b, 
		 TOP_cmpltu_i_r, 
		 TOP_cmpltu_i_b, 
		 TOP_cmpne_r_r, 
		 TOP_cmpne_r_b, 
		 TOP_cmpne_i_r, 
		 TOP_cmpne_i_b, 
		 TOP_divs, 
		 TOP_max_r, 
		 TOP_max_i, 
		 TOP_maxu_r, 
		 TOP_maxu_i, 
		 TOP_min_r, 
		 TOP_min_i, 
		 TOP_minu_r, 
		 TOP_minu_i, 
		 TOP_nandl_r_r, 
		 TOP_nandl_r_b, 
		 TOP_nandl_i_r, 
		 TOP_nandl_i_b, 
		 TOP_norl_r_r, 
		 TOP_norl_r_b, 
		 TOP_norl_i_r, 
		 TOP_norl_i_b, 
		 TOP_or_r, 
		 TOP_or_i, 
		 TOP_orc_r, 
		 TOP_orc_i, 
		 TOP_orl_r_r, 
		 TOP_orl_r_b, 
		 TOP_orl_i_r, 
		 TOP_orl_i_b, 
		 TOP_sbrk, 
		 TOP_sh1add_r, 
		 TOP_sh1add_i, 
		 TOP_sh2add_r, 
		 TOP_sh2add_i, 
		 TOP_sh3add_r, 
		 TOP_sh3add_i, 
		 TOP_sh4add_r, 
		 TOP_sh4add_i, 
		 TOP_shl_r, 
		 TOP_shl_i, 
		 TOP_shr_r, 
		 TOP_shr_i, 
		 TOP_shru_r, 
		 TOP_shru_i, 
		 TOP_slct_r, 
		 TOP_slct_i, 
		 TOP_slctf_r, 
		 TOP_slctf_i, 
		 TOP_sub_r, 
		 TOP_sub_i, 
		 TOP_syscall, 
		 TOP_sxtb_r, 
		 TOP_sxth_r, 
		 TOP_xor_r, 
		 TOP_xor_i, 
		 TOP_send_i, 
		 TOP_recv_i, 
		 TOP_mulh_r, 
		 TOP_mulh_i, 
		 TOP_mulhh_r, 
		 TOP_mulhh_i, 
		 TOP_mulhhu_r, 
		 TOP_mulhhu_i, 
		 TOP_mulhs_r, 
		 TOP_mulhs_i, 
		 TOP_mulhu_r, 
		 TOP_mulhu_i, 
		 TOP_mull_r, 
		 TOP_mull_i, 
		 TOP_mullh_r, 
		 TOP_mullh_i, 
		 TOP_mullhu_r, 
		 TOP_mullhu_i, 
		 TOP_mulll_r, 
		 TOP_mulll_i, 
		 TOP_mulllu_r, 
		 TOP_mulllu_i, 
		 TOP_mullu_r, 
		 TOP_mullu_i, 
		 TOP_ldb, 
		 TOP_ldb_d, 
		 TOP_ldbu, 
		 TOP_ldbu_d, 
		 TOP_ldh, 
		 TOP_ldh_d, 
		 TOP_ldhu, 
		 TOP_ldhu_d, 
		 TOP_ldw, 
		 TOP_ldw_d, 
		 TOP_sync, 
		 TOP_pft, 
		 TOP_prgadd, 
		 TOP_prgset, 
		 TOP_stb, 
		 TOP_sth, 
		 TOP_stw, 
		 TOP_UNDEFINED); 

  /* ===== Specification for S3_Unit Type ===== */ 
  S3_Unit = ISA_Exec_Unit_Type_Create("S3_Unit", NULL); 
  Instruction_Exec_Unit_Group(S3_Unit, 
		 TOP_nop, 
		 TOP_mov_r, 
		 TOP_mov_i, 
		 TOP_mtb, 
		 TOP_mfb, 
		 TOP_add_r, 
		 TOP_add_i, 
		 TOP_addcg, 
		 TOP_and_r, 
		 TOP_and_i, 
		 TOP_andc_r, 
		 TOP_andc_i, 
		 TOP_andl_r_r, 
		 TOP_andl_r_b, 
		 TOP_andl_i_r, 
		 TOP_andl_i_b, 
		 TOP_break, 
		 TOP_bswap_r, 
		 TOP_cmpeq_r_r, 
		 TOP_cmpeq_r_b, 
		 TOP_cmpeq_i_r, 
		 TOP_cmpeq_i_b, 
		 TOP_cmpge_r_r, 
		 TOP_cmpge_r_b, 
		 TOP_cmpge_i_r, 
		 TOP_cmpge_i_b, 
		 TOP_cmpgeu_r_r, 
		 TOP_cmpgeu_r_b, 
		 TOP_cmpgeu_i_r, 
		 TOP_cmpgeu_i_b, 
		 TOP_cmpgt_r_r, 
		 TOP_cmpgt_r_b, 
		 TOP_cmpgt_i_r, 
		 TOP_cmpgt_i_b, 
		 TOP_cmpgtu_r_r, 
		 TOP_cmpgtu_r_b, 
		 TOP_cmpgtu_i_r, 
		 TOP_cmpgtu_i_b, 
		 TOP_cmple_r_r, 
		 TOP_cmple_r_b, 
		 TOP_cmple_i_r, 
		 TOP_cmple_i_b, 
		 TOP_cmpleu_r_r, 
		 TOP_cmpleu_r_b, 
		 TOP_cmpleu_i_r, 
		 TOP_cmpleu_i_b, 
		 TOP_cmplt_r_r, 
		 TOP_cmplt_r_b, 
		 TOP_cmplt_i_r, 
		 TOP_cmplt_i_b, 
		 TOP_cmpltu_r_r, 
		 TOP_cmpltu_r_b, 
		 TOP_cmpltu_i_r, 
		 TOP_cmpltu_i_b, 
		 TOP_cmpne_r_r, 
		 TOP_cmpne_r_b, 
		 TOP_cmpne_i_r, 
		 TOP_cmpne_i_b, 
		 TOP_divs, 
		 TOP_max_r, 
		 TOP_max_i, 
		 TOP_maxu_r, 
		 TOP_maxu_i, 
		 TOP_min_r, 
		 TOP_min_i, 
		 TOP_minu_r, 
		 TOP_minu_i, 
		 TOP_nandl_r_r, 
		 TOP_nandl_r_b, 
		 TOP_nandl_i_r, 
		 TOP_nandl_i_b, 
		 TOP_norl_r_r, 
		 TOP_norl_r_b, 
		 TOP_norl_i_r, 
		 TOP_norl_i_b, 
		 TOP_or_r, 
		 TOP_or_i, 
		 TOP_orc_r, 
		 TOP_orc_i, 
		 TOP_orl_r_r, 
		 TOP_orl_r_b, 
		 TOP_orl_i_r, 
		 TOP_orl_i_b, 
		 TOP_sbrk, 
		 TOP_sh1add_r, 
		 TOP_sh1add_i, 
		 TOP_sh2add_r, 
		 TOP_sh2add_i, 
		 TOP_sh3add_r, 
		 TOP_sh3add_i, 
		 TOP_sh4add_r, 
		 TOP_sh4add_i, 
		 TOP_shl_r, 
		 TOP_shl_i, 
		 TOP_shr_r, 
		 TOP_shr_i, 
		 TOP_shru_r, 
		 TOP_shru_i, 
		 TOP_slct_r, 
		 TOP_slct_i, 
		 TOP_slctf_r, 
		 TOP_slctf_i, 
		 TOP_sub_r, 
		 TOP_sub_i, 
		 TOP_syscall, 
		 TOP_sxtb_r, 
		 TOP_sxth_r, 
		 TOP_xor_r, 
		 TOP_xor_i, 
		 TOP_send_i, 
		 TOP_recv_i, 
		 TOP_ldb, 
		 TOP_ldb_d, 
		 TOP_ldbu, 
		 TOP_ldbu_d, 
		 TOP_ldh, 
		 TOP_ldh_d, 
		 TOP_ldhu, 
		 TOP_ldhu_d, 
		 TOP_ldw, 
		 TOP_ldw_d, 
		 TOP_sync, 
		 TOP_pft, 
		 TOP_prgadd, 
		 TOP_prgset, 
		 TOP_stb, 
		 TOP_sth, 
		 TOP_stw, 
		 TOP_imml, 
		 TOP_immr, 
		 TOP_UNDEFINED); 

  /* === All legal bundle orderings (8 of them) are specified below. */ 

  /* ===== Template 0x00 (0) ===== */ 
  ISA_Bundle_Type_Create("temp0", ".temp0", 4); 
  Slot(0, S0_Unit); 
  Slot(1, S1_Unit); 
  Slot(2, S2_Unit); 
  Slot(3, S3_Unit); 
  Stop(3); 

  /* ===== Template 0x00 (1) ===== */ 
  ISA_Bundle_Type_Create("temp1", ".temp1", 4); 
  Slot(0, S0_Unit); 
  Stop(0); 
  Slot(1, S1_Unit); 
  Slot(2, S2_Unit); 
  Slot(3, S3_Unit); 
  Stop(3); 

  /* ===== Template 0x00 (2) ===== */ 
  ISA_Bundle_Type_Create("temp2", ".temp2", 4); 
  Slot(0, S0_Unit); 
  Slot(1, S1_Unit); 
  Stop(1); 
  Slot(2, S2_Unit); 
  Slot(3, S3_Unit); 
  Stop(3); 

  /* ===== Template 0x00 (3) ===== */ 
  ISA_Bundle_Type_Create("temp3", ".temp3", 4); 
  Slot(0, S0_Unit); 
  Slot(1, S1_Unit); 
  Slot(2, S2_Unit); 
  Stop(2); 
  Slot(3, S3_Unit); 
  Stop(3); 

  /* ===== Template 0x00 (4) ===== */ 
  ISA_Bundle_Type_Create("temp4", ".temp4", 4); 
  Slot(0, S0_Unit); 
  Stop(0); 
  Slot(1, S1_Unit); 
  Stop(1); 
  Slot(2, S2_Unit); 
  Slot(3, S3_Unit); 
  Stop(3); 

  /* ===== Template 0x00 (5) ===== */ 
  ISA_Bundle_Type_Create("temp5", ".temp5", 4); 
  Slot(0, S0_Unit); 
  Stop(0); 
  Slot(1, S1_Unit); 
  Slot(2, S2_Unit); 
  Stop(2); 
  Slot(3, S3_Unit); 
  Stop(3); 

  /* ===== Template 0x00 (6) ===== */ 
  ISA_Bundle_Type_Create("temp6", ".temp6", 4); 
  Slot(0, S0_Unit); 
  Stop(0); 
  Slot(1, S1_Unit); 
  Stop(1); 
  Slot(2, S2_Unit); 
  Stop(2); 
  Slot(3, S3_Unit); 
  Stop(3); 

  /* ===== Template 0x00 (7) ===== */ 
  ISA_Bundle_Type_Create("temp7", ".temp7", 4); 
  Slot(0, S0_Unit); 
  Slot(1, S1_Unit); 
  Stop(1); 
  Slot(2, S2_Unit); 
  Stop(2); 
  Slot(3, S3_Unit); 
  Stop(3); 


  ISA_Bundle_End(); 
  return 0; 
} 
