#if defined(TARG_ST200)
    case BUILT_IN_ABSCH:
    case BUILT_IN_ABSCL:
    case BUILT_IN_ABSCW:
    case BUILT_IN_ABSH:
    case BUILT_IN_ABSL:
    case BUILT_IN_ABSW:
    case BUILT_IN_ADDCH:
    case BUILT_IN_ADDCL:
    case BUILT_IN_ADDCW:
    case BUILT_IN_ADDD:
    case BUILT_IN_ADDL:
    case BUILT_IN_ADDS:
    case BUILT_IN_ADDUL:
    case BUILT_IN_BITCLRH:
    case BUILT_IN_BITCLRW:
    case BUILT_IN_BITCNTH:
    case BUILT_IN_BITCNTW:
    case BUILT_IN_BITNOTH:
    case BUILT_IN_BITNOTW:
    case BUILT_IN_BITREVW:
    case BUILT_IN_BITSETH:
    case BUILT_IN_BITSETW:
    case BUILT_IN_BITVALH:
    case BUILT_IN_BITVALW:
    case BUILT_IN_BUILTIN__DIVUW:
    case BUILT_IN_BUILTIN__DIVW:
    case BUILT_IN_BUILTIN__MODUW:
    case BUILT_IN_BUILTIN__MODW:
    case BUILT_IN_CLAMPLW:
    case BUILT_IN_CLAMPWH:
    case BUILT_IN_DISTH:
    case BUILT_IN_DISTUH:
    case BUILT_IN_DISTUW:
    case BUILT_IN_DISTW:
    case BUILT_IN_DIVD:
    case BUILT_IN_DIVFCH:
    case BUILT_IN_DIVFCM:
    case BUILT_IN_DIVFCW:
    case BUILT_IN_DIVH:
    case BUILT_IN_DIVL:
    case BUILT_IN_DIVM:
    case BUILT_IN_DIVS:
    case BUILT_IN_DIVUH:
    case BUILT_IN_DIVUL:
    case BUILT_IN_DIVUM:
    case BUILT_IN_DIVUW:
    case BUILT_IN_DIVW:
    case BUILT_IN_DTOL:
    case BUILT_IN_DTOS:
    case BUILT_IN_DTOUL:
    case BUILT_IN_DTOUW:
    case BUILT_IN_DTOW:
    case BUILT_IN_EDGESH:
    case BUILT_IN_EDGESW:
    case BUILT_IN_EQD:
    case BUILT_IN_EQL:
    case BUILT_IN_EQS:
    case BUILT_IN_EQUL:
    case BUILT_IN_GED:
    case BUILT_IN_GEL:
    case BUILT_IN_GES:
    case BUILT_IN_GETHH:
    case BUILT_IN_GETHW:
    case BUILT_IN_GETLH:
    case BUILT_IN_GETLW:
    case BUILT_IN_GEUL:
    case BUILT_IN_GTD:
    case BUILT_IN_GTL:
    case BUILT_IN_GTS:
    case BUILT_IN_GTUL:
    case BUILT_IN_INSEQUW:
    case BUILT_IN_INSEQW:
    case BUILT_IN_INSGEUW:
    case BUILT_IN_INSGEW:
    case BUILT_IN_INSGTUW:
    case BUILT_IN_INSGTW:
    case BUILT_IN_INSLEUW:
    case BUILT_IN_INSLEW:
    case BUILT_IN_INSLTUW:
    case BUILT_IN_INSLTW:
    case BUILT_IN_INSNEUW:
    case BUILT_IN_INSNEW:
    case BUILT_IN_LED:
    case BUILT_IN_LEL:
    case BUILT_IN_LES:
    case BUILT_IN_LEUL:
    case BUILT_IN_LTD:
    case BUILT_IN_LTL:
    case BUILT_IN_LTOD:
    case BUILT_IN_LTOS:
    case BUILT_IN_LTS:
    case BUILT_IN_LTUL:
    case BUILT_IN_LZCNTH:
    case BUILT_IN_LZCNTL:
    case BUILT_IN_LZCNTW:
    case BUILT_IN_MADDS:
    case BUILT_IN_MAFCW:
    case BUILT_IN_MAXD:
    case BUILT_IN_MAXH:
    case BUILT_IN_MAXL:
    case BUILT_IN_MAXS:
    case BUILT_IN_MAXUH:
    case BUILT_IN_MAXUL:
    case BUILT_IN_MAXUW:
    case BUILT_IN_MAXW:
    case BUILT_IN_MIND:
    case BUILT_IN_MINH:
    case BUILT_IN_MINL:
    case BUILT_IN_MINS:
    case BUILT_IN_MINUH:
    case BUILT_IN_MINUL:
    case BUILT_IN_MINUW:
    case BUILT_IN_MINW:
    case BUILT_IN_MODFCH:
    case BUILT_IN_MODFCM:
    case BUILT_IN_MODFCW:
    case BUILT_IN_MODH:
    case BUILT_IN_MODL:
    case BUILT_IN_MODM:
    case BUILT_IN_MODUH:
    case BUILT_IN_MODUL:
    case BUILT_IN_MODUM:
    case BUILT_IN_MODUW:
    case BUILT_IN_MODW:
    case BUILT_IN_MPFCW:
    case BUILT_IN_MPFCWL:
    case BUILT_IN_MPFML:
    case BUILT_IN_MPFRCH:
    case BUILT_IN_MPML:
    case BUILT_IN_MPUML:
    case BUILT_IN_MSUBS:
    case BUILT_IN_MULD:
    case BUILT_IN_MULFCH:
    case BUILT_IN_MULFCM:
    case BUILT_IN_MULFCW:
    case BUILT_IN_MULH:
    case BUILT_IN_MULHH:
    case BUILT_IN_MULHUH:
    case BUILT_IN_MULHUW:
    case BUILT_IN_MULHW:
    case BUILT_IN_MULL:
    case BUILT_IN_MULM:
    case BUILT_IN_MULN:
    case BUILT_IN_MULS:
    case BUILT_IN_MULUH:
    case BUILT_IN_MULUL:
    case BUILT_IN_MULUM:
    case BUILT_IN_MULUN:
    case BUILT_IN_MULUW:
    case BUILT_IN_MULW:
    case BUILT_IN_NEARCLW:
    case BUILT_IN_NEARCWH:
    case BUILT_IN_NEARLW:
    case BUILT_IN_NEARWH:
    case BUILT_IN_NED:
    case BUILT_IN_NEGCH:
    case BUILT_IN_NEGCL:
    case BUILT_IN_NEGCW:
    case BUILT_IN_NEGL:
    case BUILT_IN_NEGUL:
    case BUILT_IN_NEL:
    case BUILT_IN_NES:
    case BUILT_IN_NEUL:
    case BUILT_IN_NORMH:
    case BUILT_IN_NORML:
    case BUILT_IN_NORMW:
    case BUILT_IN_PRIORH:
    case BUILT_IN_PRIORL:
    case BUILT_IN_PRIORW:
    case BUILT_IN_PUTHL:
    case BUILT_IN_PUTHW:
    case BUILT_IN_PUTLL:
    case BUILT_IN_PUTLW:
    case BUILT_IN_ROTLH:
    case BUILT_IN_ROTLW:
    case BUILT_IN_ROUNDCLW:
    case BUILT_IN_ROUNDCWH:
    case BUILT_IN_ROUNDLW:
    case BUILT_IN_ROUNDWH:
    case BUILT_IN_SHLCH:
    case BUILT_IN_SHLCW:
    case BUILT_IN_SHLL:
    case BUILT_IN_SHLUL:
    case BUILT_IN_SHLW:
    case BUILT_IN_SHRL:
    case BUILT_IN_SHRRH:
    case BUILT_IN_SHRRW:
    case BUILT_IN_SHRUL:
    case BUILT_IN_SHRUW:
    case BUILT_IN_SHRW:
    case BUILT_IN_SQRTD:
    case BUILT_IN_SQRTS:
    case BUILT_IN_ST220ADDCG:
    case BUILT_IN_ST220DIVS:
    case BUILT_IN_ST220MULHHS:
    case BUILT_IN_ST220MULHS:
    case BUILT_IN_ST220MULLHUS:
    case BUILT_IN_ST220MULLU:
    case BUILT_IN_ST220PFT:
    case BUILT_IN_ST220PRGADD:
    case BUILT_IN_ST220PRGINS:
    case BUILT_IN_ST220PRGSET:
    case BUILT_IN_ST220SYNC:
    case BUILT_IN_ST220SYNCINS:
    case BUILT_IN_ST220SYSCALL:
    case BUILT_IN_STOD:
    case BUILT_IN_STOL:
    case BUILT_IN_STOUL:
    case BUILT_IN_STOUW:
    case BUILT_IN_STOW:
    case BUILT_IN_SUBCH:
    case BUILT_IN_SUBCL:
    case BUILT_IN_SUBCW:
    case BUILT_IN_SUBD:
    case BUILT_IN_SUBL:
    case BUILT_IN_SUBS:
    case BUILT_IN_SUBUL:
    case BUILT_IN_SWAPBH:
    case BUILT_IN_SWAPBW:
    case BUILT_IN_SWAPHW:
    case BUILT_IN_ULTOD:
    case BUILT_IN_ULTOS:
    case BUILT_IN_UWTOD:
    case BUILT_IN_UWTOS:
    case BUILT_IN_WTOD:
    case BUILT_IN_WTOS:
    case BUILT_IN_XSHLH:
    case BUILT_IN_XSHLW:
    case BUILT_IN_XSHRH:
    case BUILT_IN_XSHRW:
    case BUILT_IN_ST200MUL32:
    case BUILT_IN_ST200MUL64H:
    case BUILT_IN_ST200MUL64HU:
    case BUILT_IN_ST200MULFRAC:
    case BUILT_IN_ST200PRGINSPG:
    case BUILT_IN_ST200PSWCLR:
    case BUILT_IN_ST200PSWSET:
    case BUILT_IN_NMADDS:
    case BUILT_IN_NMSUBS:
    case BUILT_IN_SQUARES:
    case BUILT_IN_RECIPS:
    case BUILT_IN_RSQRTS:
    case BUILT_IN_ASM_0:
    case BUILT_IN_ASM_1:
    case BUILT_IN_ASM_2:
    case BUILT_IN_ASM_3:
    case BUILT_IN_ASM_4:
    case BUILT_IN_ASM_5:
    case BUILT_IN_ASM_6:
    case BUILT_IN_ASM_7:
    case BUILT_IN_ASM_8:
    case BUILT_IN_ASM_9:
    case BUILT_IN_ASM_10:
    case BUILT_IN_ASM_11:
    case BUILT_IN_ASM_12:
    case BUILT_IN_ASM_13:
    case BUILT_IN_ASM_14:
    case BUILT_IN_ASM_15:
  break;
#endif /* defined(TARG_ST200) */
